### ISSUE TITLE
locale("C")

### ISSUE THREAD

**Issue by yleydier** [Liris-Pleiad/libcrn#9]

**Comment by yleydier** [comment]
Fait sur mon fork, mais je ne peux pas tester car mon OS est en anglais.

**Comment by mtola** [comment]
Ok, je testerai ( dès que je peux rebooter ;-) ) sous mon linux, et je lancerai les tests, je te dirai...

**Comment by mtola** [comment]
Ça marche sous mon Ubuntu 16.04 en VF.

Mais ce pb était surtout un plantage Windows à l'origine non ? En tout cas, ça marche aussi sous mon Windows également.

**Comment by mtola** [comment]
Je ferme donc.
